# Generated by Django 6.0.6 on 2026-06-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaccionesdatos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("doble", "Doble"),
                    ("triple", "Triple"),
                    ("cuadruple", "Cuadruple"),
                    ("suite", "Suite"),
                    ("familiar", "Familiar"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
