# Generated by Django 6.0.6 on 2026-06-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaccionesdatos", "0002_alter_habitacion_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("doble_matrimonial", "Doble matrimonial"),
                    ("doble_individual", "Doble Individual"),
                    ("triple", "Triple"),
                    ("cuadruple", "Cuádruple"),
                    ("suite", "Suite"),
                    ("familiar", "Familiar"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
