# Generated by Django 6.0.6 on 2026-06-24 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaccionesdatos", "0003_alter_habitacion_tipo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Total"
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaccionesdatos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que reserva",
            ),
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=200, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=200, verbose_name="Apellidos"),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("dni", "DNI"),
                            ("pasaporte", "Pasaporte"),
                            ("cedula", "Cédula"),
                            ("otros", "Otros"),
                        ],
                        default="dni",
                        max_length=20,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de documento"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "direccion",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cliente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario (si está registrado)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AddField(
            model_name="reserva",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaccionesdatos",
                to="transaccionesdatos.cliente",
                verbose_name="Cliente",
            ),
        ),
    ]
