# Generated by Django 6.0.6 on 2026-06-24 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaccionesdatos", "0004_alter_reserva_total_alter_reserva_usuario_cliente_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha de fin"),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="fecha_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de inicio"
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="habitacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaccionesdatos",
                to="transaccionesdatos.habitacion",
                verbose_name="Habitación",
            ),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas_usuario",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que reserva",
            ),
        ),
    ]
