# Generated by Django 6.0.6 on 2026-06-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "transaccionesdatos",
            "0005_alter_reserva_fecha_fin_alter_reserva_fecha_inicio_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="direccion",
        ),
    ]
