# Generated by Django 6.0.6 on 2026-06-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaccionesdatos", "0006_remove_cliente_direccion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habitacion",
            name="esta_disponible",
        ),
        migrations.AddField(
            model_name="habitacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("reservada", "Reservada"),
                    ("ocupada", "Ocupada"),
                    ("mantenimiento", "En mantenimiento"),
                ],
                default="disponible",
                max_length=20,
                verbose_name="Estado de la habitación",
            ),
        ),
    ]
