# Generated by Django 6.0.6 on 2026-06-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transaccionesdatos",
            "0007_remove_habitacion_esta_disponible_habitacion_estado",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("producto", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=50)),
                ("vendedor", models.CharField(max_length=100)),
                ("cantidad", models.IntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("region", models.CharField(max_length=50)),
                ("cliente", models.CharField(max_length=100)),
                ("metodo_pago", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AlterModelOptions(
            name="reserva",
            options={},
        ),
    ]
